service:
  name: gateway
  port: 8080

image:
  repository: "thefungun36/gateway"
  pullPolicy: Always
  tag: "latest"

ingress:
  host: "rsoi-lab.ru"

data:
  DATABASE_URL: "postgresql://program:test@postgresql.default.svc.cluster.local:5432/reservations"
