name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Set up k8s
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.16.4'

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH
          echo "Yandex Cloud CLI installed and added to PATH"

      - name: Docker build
        run: docker compose build

      - name: Publish to Docker Hub
        run: |
          docker login -u thefungun36 -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker compose push

      - name: Publish to Yandex Cloud
        timeout-minutes: 10
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$YC_SERVICE_ACCOUNT_KEY" > sa-key.json
          export YC_SERVICE_ACCOUNT_KEY_FILE=sa-key.json
          yc config set service-account-key sa-key.json
          yc config set cloud-id b1g8mtnhnv5kjsmnar76
          yc config set folder-id b1gilib9d4viuklh7479
          mkdir -p ~/.kube
          yc managed-kubernetes cluster list
          yc managed-kubernetes cluster get-credentials catsgn5bmstda79f5md1 --external --force > ~/.kube/config
          kubectl cluster-info --kubeconfig ~/.kube/config

          helm uninstall payment || true
          helm install payment ./helm-rsoi-lab -f ./helm-rsoi-lab/values-payment.yaml
          helm uninstall loyalty || true
          helm install loyalty ./helm-rsoi-lab -f ./helm-rsoi-lab/values-loyalty.yaml
          helm uninstall reservation || true
          helm install reservation ./helm-rsoi-lab -f ./helm-rsoi-lab/values-reservation.yaml
          helm uninstall gateway || true
          helm install gateway ./helm-rsoi-lab -f ./helm-rsoi-lab/values-gateway.yaml
          sleep 25

          sudo bash -c "echo '158.160.143.187 rsoi-lab.ru' >> /etc/hosts"

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
